### ISSUE TITLE
`npm run cmake_all` automatically

### ISSUE THREAD

**Issue by dillionverma** [p2pderivatives/cfd-dlc-js#53]
When I use this package as a dependency, I have to always `cd node_modules/cfd-dlc-js` and run `npm run cmake_all` manually. Can this be added to the install script so it happens automatically? 

It ends up being a hassle in build scripts when deploying the code to production.

**Comment by Tibo-lg** [comment]
If you point to this mirror repo in your package.json it should be able to use the pre-built binaries and thus avoid having to build things manually: https://github.com/cryptogarageinc/cfd-dlc-js/releases

Otherwise you should also be able to do the build in the "preinstall" step of your package?

**Comment by matthewjablack** [comment]
Thanks @Tibo-lg, we were missing a release for our fork
